[package]
name = "ChainlinkPlatform"
version = "1.0.0"
authors = []

# Thala Modified
[addresses]
platform = "0x516e771e1b4a903afe74c27d057c65849ecc1383782f6642d7ff21425f4f9c99"
owner = "0xcafe"

[dev-addresses]
platform = "0x100"
owner = "0xcafe"

[dependencies]
AptosFramework = { git = "https://github.com/aptos-labs/aptos-core.git", rev = "34025227eb5367c449bf9dae3cd226fe5c187904", subdir = "aptos-move/framework/aptos-framework" }

[dev-dependencies]
