[package]
name = "ChainlinkPlatform"
version = "1.0.0"
authors = []

# Thala Modified
[addresses]
platform = "0x9976bb288ed9177b542d568fa1ac386819dc99141630e582315804840f41928a"
owner = "0xb3c4f75936dc2f8af0398408a7ef739cca2601439be9100eb7a792c475923d1"

[dev-addresses]
platform = "0x100"
owner = "0xcafe"

[dependencies]
AptosFramework = { git = "https://github.com/aptos-labs/aptos-core.git", rev = "34025227eb5367c449bf9dae3cd226fe5c187904", subdir = "aptos-move/framework/aptos-framework" }

[dev-dependencies]
